apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    uid: tempo-datasource
    editable: true
    isDefault: false
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: 'cf5ynk7bnqepse'
      tracesToMetrics:
        datasourceUid: 'cf5ynk7bnqepse'
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
        filterByTraceID: false
        filterBySpanID: false
        tags:
          - key: service.name
            value: service
      tracesToLogsV2:
        datasourceUid: ''
      search:
        hide: false
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: ''
