services:
  db:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${DATA_ROOT}/postgres:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - internal-net
    ports:
      - "5432:5432"

  pgbouncer:
    image: edoburu/pgbouncer:latest
    container_name: pgbouncer
    restart: always
    depends_on:
      - db
    volumes:
      - ./components/pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini:ro
      - ./components/pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt:ro
    ports:
      - "6432:6432"
    networks:
      - internal-net

  kong:
    image: rebranded-kong:3.14
    build:
      context: ./components/kong/kong-manager
      dockerfile: Dockerfile
    container_name: kong
    restart: always
    depends_on:
      - pgbouncer
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: pgbouncer
      KONG_PG_PORT: 6432
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD}
      KONG_PG_DATABASE: kong
      KONG_AUTO_MIGRATE: "true"
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_ADMIN_GUI_LISTEN: 0.0.0.0:8002, 0.0.0.0:8445 ssl
      KONG_ADMIN_GUI_URL: http://localhost:8002
      KONG_ADMIN_GUI_API_URL: http://localhost:8001
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PLUGINS: bundled, prometheus, oidc, kong-openid-connect
      KONG_STATUS_LISTEN: 0.0.0.0:8100
      KONG_TRACING_INSTRUMENTATIONS: all
      KONG_TRACING_SAMPLING_RATE: "1.0"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
      - "8445:8445"
      - "8100:8100"
    networks:
      - internal-net

  tempo:
    image: grafana/tempo:2.6.0
    container_name: tempo
    restart: always
    command: ["-config.file=/etc/tempo/tempo.yml"]
    volumes:
      - ./components/tempo/tempo.yml:/etc/tempo/tempo.yml:ro
      - ${DATA_ROOT}/tempo:/var/tempo
    ports:
      - "3200:3200"   # Tempo API
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    networks:
      - internal-net

  loki:
    image: grafana/loki:3.5.0
    container_name: loki
    restart: always
    command: ["-config.file=/etc/loki/loki.yml"]
    volumes:
      - ./components/loki/loki.yml:/etc/loki/loki.yml:ro
      - ${DATA_ROOT}/loki:/loki
    ports:
      - "3100:3100"   # Loki HTTP API
      - "9096:9096"   # Loki gRPC
    networks:
      - internal-net

  promtail:
    image: grafana/promtail:3.5.0
    container_name: promtail
    restart: always
    depends_on:
      - loki
    command: ["-config.file=/etc/promtail/promtail.yml"]
    volumes:
      - ./components/promtail/promtail.yml:/etc/promtail/promtail.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    networks:
      - internal-net

  keycloak:
    image: keycloak/keycloak:20.0.5
    container_name: keycloak
    command: start-dev
    depends_on:
      - pgbouncer
    ports:
      - "8080:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://pgbouncer:6432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_LOG_LEVEL: DEBUG
      KC_PROXY: edge
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_METRICS_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
    restart: unless-stopped
    networks:
      - internal-net

  node-exporter:
    image: prom/node-exporter:v1.8.0
    container_name: node-exporter
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($|/)
    networks:
      - internal-net

  prometheus:
    image: prom/prometheus:v3.0.0
    container_name: prometheus
    restart: always
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-otlp-receiver'
    depends_on:
      - kong
    volumes:
      - ./components/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ${DATA_ROOT}/prometheus:/prometheus
    ports:
      - "9090:9090"
    networks:
      - internal-net

  grafana:
    image: grafana/grafana:12.3.0
    container_name: grafana-server
    restart: always
    depends_on:
      - prometheus
      - pgbouncer
      - tempo
      - loki
    volumes:
      - ./components/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./components/grafana/dashboards:/var/lib/grafana/dashboards:ro
      - ${DATA_ROOT}/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "false"
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: pgbouncer:6432
      GF_DATABASE_NAME: grafana
      GF_DATABASE_USER: grafana
      GF_DATABASE_PASSWORD: ${GF_DATABASE_PASSWORD}
    networks:
      - internal-net

  pg_exporter:
    image: ghcr.io/nbari/pg_exporter:latest
    container_name: pg_exporter
    restart: always
    depends_on:
      - db
    environment:
      PG_EXPORTER_DSN: "postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/postgres?sslmode=disable"
    command:
      - --collector.locks
      - --collector.database
      - --collector.stat
      - --collector.replication
      - --collector.index
      - --collector.statements
      - --collector.tls
      - --collector.exporter
      - --collector.activity
    ports:
      - "9432:9432"
    networks:
      - internal-net

networks:
  internal-net:
