{
 "title": "Kong API Gateway",
 "description": "Dashboard that graphs metrics exported via Prometheus plugin in Kong (http://github.com/kong/kong)",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(kong_http_requests_total,service)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(kong_nginx_connections_total,instance)"
    }
   },
   {
    "name": "route",
    "query": {
     "query": "label_values(kong_http_requests_total,route)"
    }
   },
   {
    "name": "upstream",
    "query": {
     "query": "label_values(kong_upstream_target_health, upstream)"
    }
   },
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Kong Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kong_node_info{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Datastore Health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kong_datastore_reachable{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Current RPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(kong_http_requests_total{instance=~\"$instance\"}[1m]))"
    }
   ]
  },
  {
   "title": "Error Rate %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(kong_http_requests_total{code=~\"[45]..\",instance=~\"$instance\"}[1m])) / sum(rate(kong_http_requests_total{instance=~\"$instance\"}[1m])) * 100"
    }
   ]
  },
  {
   "title": "Upstream Success %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(kong_http_requests_total{code=~\"[23]..\",instance=~\"$instance\"}[1m])) / sum(rate(kong_http_requests_total{instance=~\"$instance\"}[1m])) * 100"
    }
   ]
  },
  { "title": "Request Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Total requests per second (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(kong_http_requests_total{instance=~\"$instance\"}[1m]))",
     "legendFormat": "Requests/second"
    }
   ]
  },
  {
   "title": "RPS per route/service ($service)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(kong_http_requests_total{service=~\"$service\", route=~\"$route\", instance=~\"$instance\"}[1m])) by (service)",
     "legendFormat": "service:{{service}}"
    },
    {
     "expr": "sum(rate(kong_http_requests_total{service=~\"$service\", route=~\"$route\", instance=~\"$instance\"}[1m])) by (route)",
     "legendFormat": "route:{{route}}"
    }
   ]
  },
  {
   "title": "RPS per route/service by status code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(kong_http_requests_total{service=~\"$service\", route=~\"$route\", instance=~\"$instance\"}[1m])) by (service,code)",
     "legendFormat": "service:{{service}}-{{code}}"
    },
    {
     "expr": "sum(rate(kong_http_requests_total{service=~\"$service\", route=~\"$route\", instance=~\"$instance\"}[1m])) by (route,code)",
     "legendFormat": "route:{{route}}-{{code}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Error Rate (4xx + 5xx)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(kong_http_requests_total{code=~\"4..\",service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service)",
     "legendFormat": "4xx-{{service}}"
    },
    {
     "expr": "sum(rate(kong_http_requests_total{code=~\"5..\",service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service)",
     "legendFormat": "5xx-{{service}}"
    }
   ]
  },
  {
   "title": "Error Ratio %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(kong_http_requests_total{code=~\"[45]..\",service=~\"$service\",instance=~\"$instance\"}[1m])) / sum(rate(kong_http_requests_total{service=~\"$service\",instance=~\"$instance\"}[1m])) * 100",
     "legendFormat": "error %"
    }
   ]
  },
  {
   "title": "Metric Errors",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(kong_nginx_metric_errors_total{instance=~\"$instance\"}[5m])"
    }
   ]
  },
  {
   "title": "Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kong Proxy Latency across all services",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_kong_latency_ms_bucket{instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_kong_latency_ms_bucket{instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_kong_latency_ms_bucket{instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "rate(kong_kong_latency_ms_sum{instance=~\"$instance\"}[1m]) / rate(kong_kong_latency_ms_count{instance=~\"$instance\"}[1m])",
       "legendFormat": "avg"
      }
     ]
    },
    {
     "title": "Kong Proxy Latency per Service",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_kong_latency_ms_bucket{ service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service,le))",
       "legendFormat": "p90-{{service}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_kong_latency_ms_bucket{ service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service,le))",
       "legendFormat": "p95-{{service}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_kong_latency_ms_bucket{ service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service,le))",
       "legendFormat": "p99-{{service}}"
      },
      {
       "expr": "rate(kong_kong_latency_ms_sum{service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m]) / rate(kong_kong_latency_ms_count{service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])",
       "legendFormat": "avg-{{service}}"
      }
     ]
    },
    {
     "title": "Kong Proxy Latency per Route",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_kong_latency_ms_bucket{ service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route,le))",
       "legendFormat": "p90-{{route}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_kong_latency_ms_bucket{ service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route,le))",
       "legendFormat": "p95-{{route}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_kong_latency_ms_bucket{ service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route,le))",
       "legendFormat": "p99-{{route}}"
      },
      {
       "expr": "rate(kong_kong_latency_ms_sum{service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m]) / rate(kong_kong_latency_ms_count{service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])",
       "legendFormat": "avg-{{route}}"
      }
     ]
    },
    {
     "title": "Request Time across all services",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_request_latency_ms_bucket{}[1m])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_request_latency_ms_bucket{}[1m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_request_latency_ms_bucket{}[1m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "rate(kong_request_latency_ms_sum[1m]) / rate(kong_request_latency_ms_count[1m])",
       "legendFormat": "avg"
      }
     ]
    },
    {
     "title": "Request Time per service",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_request_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service,le))",
       "legendFormat": "p90-{{service}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_request_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service,le))",
       "legendFormat": "p95-{{service}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_request_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service,le))",
       "legendFormat": "p99-{{service}}"
      },
      {
       "expr": "rate(kong_request_latency_ms_sum{service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m]) / rate(kong_request_latency_ms_count{service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])",
       "legendFormat": "avg-{{service}}"
      }
     ]
    },
    {
     "title": "Request Time per Route",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_request_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route,le))",
       "legendFormat": "p90-{{route}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_request_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route,le))",
       "legendFormat": "p95-{{route}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_request_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route,le))",
       "legendFormat": "p99-{{route}}"
      },
      {
       "expr": "rate(kong_request_latency_ms_sum{service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m]) / rate(kong_request_latency_ms_count{service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])",
       "legendFormat": "avg-{{route}}"
      }
     ]
    },
    {
     "title": "Upstream time across all services",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_upstream_latency_ms_bucket{}[1m])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_upstream_latency_ms_bucket{}[1m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_upstream_latency_ms_bucket{}[1m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "rate(kong_upstream_latency_ms_sum[1m]) / rate(kong_upstream_latency_ms_count[1m])",
       "legendFormat": "avg"
      }
     ]
    },
    {
     "title": "Upstream Time across per service",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_upstream_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service,le))",
       "legendFormat": "p90-{{service}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_upstream_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service,le))",
       "legendFormat": "p95-{{service}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_upstream_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service,le))",
       "legendFormat": "p99-{{service}}"
      },
      {
       "expr": "rate(kong_upstream_latency_ms_sum{service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m]) / rate(kong_upstream_latency_ms_count{service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])",
       "legendFormat": "avg-{{service}}"
      }
     ]
    },
    {
     "title": "Upstream Time across per Route",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_upstream_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route,le))",
       "legendFormat": "p90-{{route}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_upstream_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route,le))",
       "legendFormat": "p95-{{route}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_upstream_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route,le))",
       "legendFormat": "p99-{{route}}"
      },
      {
       "expr": "rate(kong_upstream_latency_ms_sum{service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m]) / rate(kong_upstream_latency_ms_count{service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])",
       "legendFormat": "avg-{{route}}"
      }
     ]
    },
    {
     "title": "Request Latency Distribution (Heatmap)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "sum(increase(kong_request_latency_ms_bucket{service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Kong Proxy Latency Distribution (Heatmap)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "sum(increase(kong_kong_latency_ms_bucket{instance=~\"$instance\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  { "title": "Bandwidth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Total Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(kong_bandwidth_bytes{instance=~\"$instance\"}[1m])) by (direction)",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Egress per service/route",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(kong_bandwidth_bytes{direction=\"egress\", service =~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service)",
     "legendFormat": "service:{{service}}"
    },
    {
     "expr": "sum(irate(kong_bandwidth_bytes{direction=\"egress\", service =~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route)",
     "legendFormat": "route:{{route}}"
    }
   ]
  },
  {
   "title": "Ingress per service/route",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(kong_bandwidth_bytes{direction=\"ingress\", service =~\"$service\"}[1m])) by (service)",
     "legendFormat": "serive:{{service}}"
    },
    {
     "expr": "sum(irate(kong_bandwidth_bytes{direction=\"ingress\", service =~\"$service\", route=~\"$route\"}[1m])) by (route)",
     "legendFormat": "route:{{route}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Lua Worker VM Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kong_memory_workers_lua_vms_bytes{instance=~\"$instance\"}",
     "legendFormat": "pid:{{pid}}"
    }
   ]
  },
  {
   "title": "Shared Dict Usage %",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kong_memory_lua_shared_dict_bytes{instance=~\"$instance\"} / kong_memory_lua_shared_dict_total_bytes{instance=~\"$instance\"} * 100",
     "legendFormat": "{{shared_dict}}"
    }
   ]
  },
  { "title": "Nginx", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Nginx connection state",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(kong_nginx_connections_total{state=~\"active|reading|writing|waiting\", instance=~\"$instance\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Total Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kong_nginx_connections_total{state=\"total\", instance=~\"$instance\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Handled Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kong_nginx_connections_total{state=\"handled\", instance=~\"$instance\"})",
     "legendFormat": "Handled"
    }
   ]
  },
  {
   "title": "Nginx Timers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "kong_nginx_timers{instance=~\"$instance\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Dropped Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 82 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kong_nginx_connections_total{state=\"total\", instance=~\"$instance\"}) - sum(kong_nginx_connections_total{state=\"handled\", instance=~\"$instance\"})",
     "legendFormat": "dropped"
    }
   ]
  }
 ]
}