{
 "title": "Kong API Gateway",
 "description": "Dashboard that graphs metrics exported via Prometheus plugin in Kong (http://github.com/kong/kong)",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(http_server_request_count_total, kong_service_name)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(http_server_request_count_total,instance)"
    }
   },
   {
    "name": "route",
    "query": {
     "query": "label_values(http_server_request_count_total, kong_route_name)"
    }
   },
   {
    "name": "upstream",
    "query": {
     "query": "label_values(kong_latency_upstream_seconds_count, kong_upstream_target_health)"
    }
   },
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Kong Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "target_info{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Datastore Health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kong_db_connection_status_ratio{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Current RPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_count_total{instance=~\"$instance\"}[1m]))"
    }
   ]
  },
  {
   "title": "Error Rate %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_count_total{http_response_status_code=~\"[45]..\",instance=~\"$instance\"}[1m])) / sum(rate(http_server_request_count_total{instance=~\"$instance\"}[1m])) * 100"
    }
   ]
  },
  {
   "title": "Upstream Success %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_count_total{http_response_status_code=~\"[23]..\",instance=~\"$instance\"}[1m])) / sum(rate(http_server_request_count_total{instance=~\"$instance\"}[1m])) * 100"
    }
   ]
  },
  { "title": "Request Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Total requests per second (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_count_total{instance=~\"$instance\"}[1m]))",
     "legendFormat": "Requests/second"
    }
   ]
  },
  {
   "title": "RPS per route/service ($service)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_count_total{kong_service_name=~\"$service\", kong_route_name=~\"$route\", instance=~\"$instance\"}[1m])) by (kong_service_name)",
     "legendFormat": "service:{{kong_service_name}}"
    },
    {
     "expr": "sum(rate(http_server_request_count_total{kong_service_name=~\"$service\", kong_route_name=~\"$route\", instance=~\"$instance\"}[1m])) by (kong_route_name)",
     "legendFormat": "route:{{kong_route_name}}"
    }
   ]
  },
  {
   "title": "RPS per route/service by status code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_count_total{kong_service_name=~\"$service\", kong_route_name=~\"$route\", instance=~\"$instance\"}[1m])) by (kong_service_name,http_response_status_code)",
     "legendFormat": "service:{{kong_service_name}}-{{http_response_status_code}}"
    },
    {
     "expr": "sum(rate(http_server_request_count_total{kong_service_name=~\"$service\", kong_route_name=~\"$route\", instance=~\"$instance\"}[1m])) by (kong_route_name,http_response_status_code)",
     "legendFormat": "route:{{kong_route_name}}-{{http_response_status_code}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Error Rate (4xx + 5xx)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_count_total{http_response_status_code=~\"4..\",kong_service_name=~\"$service\",kong_route_name=~\"$route\",instance=~\"$instance\"}[1m])) by (kong_service_name)",
     "legendFormat": "4xx-{{kong_service_name}}"
    },
    {
     "expr": "sum(rate(http_server_request_count_total{http_response_status_code=~\"5..\",kong_service_name=~\"$service\",kong_route_name=~\"$route\",instance=~\"$instance\"}[1m])) by (kong_service_name)",
     "legendFormat": "5xx-{{kong_service_name}}"
    }
   ]
  },
  {
   "title": "Error Ratio %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_count_total{http_response_status_code=~\"[45]..\",kong_service_name=~\"$service\",instance=~\"$instance\"}[1m])) / sum(rate(http_server_request_count_total{kong_service_name=~\"$service\",instance=~\"$instance\"}[1m])) * 100",
     "legendFormat": "error %"
    }
   ]
  },
  {
   "title": "Metric Errors",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(kong_nginx_metric_errors_total{instance=~\"$instance\"}[5m])"
    }
   ]
  },
  {
   "title": "Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kong Proxy Latency across all services",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_latency_total_seconds_bucket{instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_latency_total_seconds_bucket{instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_latency_total_seconds_bucket{instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "rate(kong_latency_total_seconds_sum{instance=~\"$instance\"}[1m]) / rate(kong_latency_total_seconds_count{instance=~\"$instance\"}[1m])",
       "legendFormat": "avg"
      }
     ]
    },
    {
     "title": "Kong Proxy Latency per Service",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_latency_total_seconds_bucket{ kong_service_name=~\"$service\",kong_route_name=~\"$route\",instance=~\"$instance\"}[1m])) by (kong_service_name,le))",
       "legendFormat": "p90-{{kong_service_name}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_latency_total_seconds_bucket{ kong_service_name=~\"$service\",kong_route_name=~\"$route\",instance=~\"$instance\"}[1m])) by (kong_service_name,le))",
       "legendFormat": "p95-{{kong_service_name}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_latency_total_seconds_bucket{ kong_service_name=~\"$service\",kong_route_name=~\"$route\",instance=~\"$instance\"}[1m])) by (kong_service_name,le))",
       "legendFormat": "p99-{{kong_service_name}}"
      },
      {
       "expr": "rate(kong_latency_total_seconds_sum{kong_service_name=~\"$service\",kong_route_name=~\"$route\",instance=~\"$instance\"}[1m]) / rate(kong_latency_total_seconds_count{kong_service_name=~\"$service\",kong_route_name=~\"$route\",instance=~\"$instance\"}[1m])",
       "legendFormat": "avg-{{kong_service_name}}"
      }
     ]
    },
    {
     "title": "Kong Proxy Latency per Route",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_latency_total_seconds_bucket{ kong_service_name=~\"$service\",kong_route_name=~\"$route\",instance=~\"$instance\"}[1m])) by (kong_route_name,le))",
       "legendFormat": "p90-{{kong_route_name}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_latency_total_seconds_bucket{ kong_service_name=~\"$service\",kong_route_name=~\"$route\",instance=~\"$instance\"}[1m])) by (kong_route_name,le))",
       "legendFormat": "p95-{{kong_route_name}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_latency_total_seconds_bucket{ kong_service_name=~\"$service\",kong_route_name=~\"$route\",instance=~\"$instance\"}[1m])) by (kong_route_name,le))",
       "legendFormat": "p99-{{kong_route_name}}"
      },
      {
       "expr": "rate(kong_latency_total_seconds_sum{kong_service_name=~\"$service\",kong_route_name=~\"$route\",instance=~\"$instance\"}[1m]) / rate(kong_latency_total_seconds_count{kong_service_name=~\"$service\",kong_route_name=~\"$route\",instance=~\"$instance\"}[1m])",
       "legendFormat": "avg-{{kong_route_name}}"
      }
     ]
    },
    {
     "title": "Request Time across all services",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_latency_internal_seconds_bucket{}[1m])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_latency_internal_seconds_bucket{}[1m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_latency_internal_seconds_bucket{}[1m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "rate(kong_latency_internal_seconds_sum[1m]) / rate(kong_latency_internal_seconds_count[1m])",
       "legendFormat": "avg"
      }
     ]
    },
    {
     "title": "Request Time per service",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_latency_internal_seconds_bucket{kong_service_name=~\"$service\",kong_route_name=~\"$route\",instance=~\"$instance\"}[1m])) by (kong_service_name,le))",
       "legendFormat": "p90-{{kong_service_name}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_latency_internal_seconds_bucket{kong_service_name=~\"$service\",kong_route_name=~\"$route\",instance=~\"$instance\"}[1m])) by (kong_service_name,le))",
       "legendFormat": "p95-{{kong_service_name}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_latency_internal_seconds_bucket{kong_service_name=~\"$service\",kong_route_name=~\"$route\",instance=~\"$instance\"}[1m])) by (kong_service_name,le))",
       "legendFormat": "p99-{{kong_service_name}}"
      },
      {
       "expr": "rate(kong_latency_internal_seconds_sum{kong_service_name=~\"$service\",kong_route_name=~\"$route\",instance=~\"$instance\"}[1m]) / rate(kong_latency_internal_seconds_count{kong_service_name=~\"$service\",kong_route_name=~\"$route\",instance=~\"$instance\"}[1m])",
       "legendFormat": "avg-{{kong_service_name}}"
      }
     ]
    },
    {
     "title": "Request Time per Route",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_latency_internal_seconds_bucket{kong_service_name=~\"$service\",kong_route_name=~\"$route\",instance=~\"$instance\"}[1m])) by (kong_route_name,le))",
       "legendFormat": "p90-{{kong_route_name}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_latency_internal_seconds_bucket{kong_service_name=~\"$service\",kong_route_name=~\"$route\",instance=~\"$instance\"}[1m])) by (kong_route_name,le))",
       "legendFormat": "p95-{{kong_route_name}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_latency_internal_seconds_bucket{kong_service_name=~\"$service\",kong_route_name=~\"$route\",instance=~\"$instance\"}[1m])) by (kong_route_name,le))",
       "legendFormat": "p99-{{kong_route_name}}"
      },
      {
       "expr": "rate(kong_latency_internal_seconds_sum{kong_service_name=~\"$service\",kong_route_name=~\"$route\",instance=~\"$instance\"}[1m]) / rate(kong_latency_internal_seconds_count{kong_service_name=~\"$service\",kong_route_name=~\"$route\",instance=~\"$instance\"}[1m])",
       "legendFormat": "avg-{{kong_route_name}}"
      }
     ]
    },
    {
     "title": "Upstream time across all services",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_latency_upstream_seconds_bucket{}[1m])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_latency_upstream_seconds_bucket{}[1m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_latency_upstream_seconds_bucket{}[1m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "rate(kong_latency_upstream_seconds_sum[1m]) / rate(kong_latency_upstream_seconds_count[1m])",
       "legendFormat": "avg"
      }
     ]
    },
    {
     "title": "Upstream Time across per service",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_latency_upstream_seconds_bucket{kong_service_name=~\"$service\",kong_route_name=~\"$route\",instance=~\"$instance\"}[1m])) by (kong_service_name,le))",
       "legendFormat": "p90-{{kong_service_name}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_latency_upstream_seconds_bucket{kong_service_name=~\"$service\",kong_route_name=~\"$route\",instance=~\"$instance\"}[1m])) by (kong_service_name,le))",
       "legendFormat": "p95-{{kong_service_name}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_latency_upstream_seconds_bucket{kong_service_name=~\"$service\",kong_route_name=~\"$route\",instance=~\"$instance\"}[1m])) by (kong_service_name,le))",
       "legendFormat": "p99-{{kong_service_name}}"
      },
      {
       "expr": "rate(kong_latency_upstream_seconds_sum{kong_service_name=~\"$service\",kong_route_name=~\"$route\",instance=~\"$instance\"}[1m]) / rate(kong_latency_upstream_seconds_count{kong_service_name=~\"$service\",kong_route_name=~\"$route\",instance=~\"$instance\"}[1m])",
       "legendFormat": "avg-{{kong_service_name}}"
      }
     ]
    },
    {
     "title": "Upstream Time across per Route",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_latency_upstream_seconds_bucket{kong_service_name=~\"$service\",kong_route_name=~\"$route\",instance=~\"$instance\"}[1m])) by (kong_route_name,le))",
       "legendFormat": "p90-{{kong_route_name}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_latency_upstream_seconds_bucket{kong_service_name=~\"$service\",kong_route_name=~\"$route\",instance=~\"$instance\"}[1m])) by (kong_route_name,le))",
       "legendFormat": "p95-{{kong_route_name}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_latency_upstream_seconds_bucket{kong_service_name=~\"$service\",kong_route_name=~\"$route\",instance=~\"$instance\"}[1m])) by (kong_route_name,le))",
       "legendFormat": "p99-{{kong_route_name}}"
      },
      {
       "expr": "rate(kong_latency_upstream_seconds_sum{kong_service_name=~\"$service\",kong_route_name=~\"$route\",instance=~\"$instance\"}[1m]) / rate(kong_latency_upstream_seconds_count{kong_service_name=~\"$service\",kong_route_name=~\"$route\",instance=~\"$instance\"}[1m])",
       "legendFormat": "avg-{{kong_route_name}}"
      }
     ]
    },
    {
     "title": "Request Latency Distribution (Heatmap)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "sum(increase(kong_latency_internal_seconds_bucket{kong_service_name=~\"$service\",kong_route_name=~\"$route\",instance=~\"$instance\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Kong Proxy Latency Distribution (Heatmap)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "sum(increase(kong_latency_total_seconds_bucket{instance=~\"$instance\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  { "title": "Bandwidth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Total Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(http_server_response_size_bytes_sum{instance=~\"$instance\"}[1m])) by (direction)",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Egress per service/route",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(http_server_response_size_bytes_sum{kong_service_name=~\"$service\",kong_route_name=~\"$route\",instance=~\"$instance\"}[1m])) by (kong_service_name)",
     "legendFormat": "service:{{kong_service_name}}"
    },
    {
     "expr": "sum(irate(http_server_response_size_bytes_sum{kong_service_name=~\"$service\",kong_route_name=~\"$route\",instance=~\"$instance\"}[1m])) by (kong_route_name)",
     "legendFormat": "route:{{kong_route_name}}"
    }
   ]
  },
  {
   "title": "Ingress per service/route",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(http_server_request_size_bytes_sum{kong_service_name=~\"$service\"}[1m])) by (kong_service_name)",
     "legendFormat": "serive:{{kong_service_name}}"
    },
    {
     "expr": "sum(irate(http_server_request_size_bytes_sum{kong_service_name=~\"$service\", kong_route_name=~\"$route\"}[1m])) by (kong_route_name)",
     "legendFormat": "route:{{kong_route_name}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Lua Worker VM Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kong_memory_workers_lua_vm_bytes{instance=~\"$instance\"}",
     "legendFormat": "pid:{{kong_pid}}"
    }
   ]
  },
  {
   "title": "Shared Dict Usage %",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kong_shared_dict_usage_bytes{instance=~\"$instance\"} / kong_shared_dict_size_bytes{instance=~\"$instance\"} * 100",
     "legendFormat": "{{kong_shared_dict_name}}"
    }
   ]
  },
  { "title": "Nginx", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Nginx connection state",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(kong_nginx_connection_count{kong_connection_state=~\"active|reading|writing|waiting\", instance=~\"$instance\"}) by (kong_connection_state)",
     "legendFormat": "{{kong_connection_state}}"
    }
   ]
  },
  {
   "title": "Total Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kong_nginx_connection_count{kong_connection_state=\"total\", instance=~\"$instance\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Handled Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kong_nginx_connection_count{kong_connection_state=\"handled\", instance=~\"$instance\"})",
     "legendFormat": "Handled"
    }
   ]
  },
  {
   "title": "Nginx Timers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "kong_nginx_timer_count{instance=~\"$instance\"}",
     "legendFormat": "{{kong_timer_state}}"
    }
   ]
  },
  {
   "title": "Dropped Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 82 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kong_nginx_connection_count{kong_connection_state=\"total\", instance=~\"$instance\"}) - sum(kong_nginx_connection_count{kong_connection_state=\"handled\", instance=~\"$instance\"})",
     "legendFormat": "dropped"
    }
   ]
  },
  { "title": "Database & Licensing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } },
  {
   "title": "DB Entity Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kong_db_entity_count{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "DB Entity Error Rate / sec",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(kong_db_entity_error_count_total{instance=~\"$instance\"}[1m]))"
    }
   ]
  },
  {
   "title": "License Error Rate / sec",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(kong_ee_license_error_count_total{instance=~\"$instance\"}[1m]))"
    }
   ]
  }
 ]
}